version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '15:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 10
    target-branch: 'mega'
    allow:
      - dependency-type: 'all'
    commit-message:
      prefix: 'Upgrade'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'automated'
    groups:
      frontend-stack:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react*'
          - '@wxt-dev/*'
          - 'wxt'
          - 'bootstrap'
          - 'bootstrap-icons'
          - 'tailwindcss'
          - 'sass'
        update-types:
          - 'minor'
          - 'patch'
      build-tooling:
        patterns:
          - 'turbo'
          - 'typescript'
          - 'vitest'
          - '@vitest/*'
        update-types:
          - 'minor'
          - 'patch'
    versioning-strategy: 'increase'

  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'mega'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '15:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 10
    allow:
      - dependency-type: 'development'
    commit-message:
      prefix: 'Upgrade'
      include: 'scope'
    labels:
      - 'dev-dependencies'
      - 'automated'
      - 'auto-merge'
    groups: {}
    versioning-strategy: 'increase'
