import { bar, beats, barSeconds } from '../timing';
import type { Cut } from './cutTypes';
import { favoriteActions, kentuckyCard, mainPopupActions, sat } from './shared';

const b = bar;

// 16 bars: the setup, the popup, the swap out and back, why, your team, the sign-off.
const cut30: Cut = {
	id: '30',
	bars: 16,
	duration: 16 * barSeconds,
	sections: [
		{ fromBar: 1, toBar: 3, part: 'intro' },
		{ fromBar: 4, toBar: 7, part: 'build' },
		{ fromBar: 8, toBar: 8, part: 'drop' },
		{ fromBar: 9, toBar: 11, part: 'groove' },
		{ fromBar: 12, toBar: 12, part: 'break' },
		{ fromBar: 13, toBar: 13, part: 'peak' },
		{ fromBar: 14, toBar: 16, part: 'outro' },
	],
	shots: [
		{ kind: 'wall', from: 0, to: b(3) + 0.7 },
		{ kind: 'browser', from: b(3), to: b(4) },
		{ kind: 'popupOpen', from: b(4), to: b(6) },
		{ kind: 'ranked', from: b(6), to: b(7) },
		{ kind: 'assign', from: b(7), to: b(8) },
		{ kind: 'swaps', from: b(8), to: b(11) },
		{ kind: 'detail', from: b(11), to: b(12) },
		{ kind: 'favorite', from: b(12), to: b(13) },
		{ kind: 'payoff', from: b(13), to: b(14) },
		{ kind: 'endCard', from: b(14), to: b(17) },
	],
	supers: [
		{ key: 'watchOne', from: b(3) + beats(1), to: b(4) + beats(2), place: 'top' },
		{ key: 'otherGames', from: b(4) + beats(2), to: b(6), place: 'top' },
		{ key: 'powerScore', from: b(6) + beats(0.5), to: b(7), place: 'left' },
		{ key: 'switches', from: b(8) + beats(1), to: b(9), place: 'top' },
		{ key: 'andBack', from: b(9) + beats(1), to: b(10), place: 'top' },
		{ key: 'seeWhy', from: b(11), to: b(12), place: 'left' },
		{ key: 'gotTeam', from: b(12), to: b(13), place: 'left' },
	],
	popups: [
		{
			id: 'main',
			page: 'popup',
			loadAt: b(4),
			profile: 'plain',
			reveal: 'quick',
			registered: false,
			clock: [
				{ at: b(4), slate: sat('7:27:40') },
				{ at: b(6) + beats(1), slate: sat('7:28:30') },
				{ at: b(6) + beats(3), slate: sat('7:28:50') },
				{ at: b(7), slate: sat('7:29:30') },
				{ at: b(8) - beats(1), slate: sat('7:32:55') },
				{ at: b(8) + beats(1), slate: sat('7:33:16') },
				{ at: b(9), slate: sat('7:33:40') },
				{ at: b(9), slate: sat('7:35:05') },
				{ at: b(9) + beats(1), slate: sat('7:35:18') },
				{ at: b(10), slate: sat('7:35:40') },
				{ at: b(10), slate: sat('7:48:00') },
				{ at: b(10) + beats(1), slate: sat('7:48:11') },
				{ at: b(10) + beats(2.5), slate: sat('7:48:50') },
				{ at: b(11), slate: sat('7:49:00') },
				{ at: b(12), slate: sat('7:59:00') },
				{ at: b(13), slate: sat('8:02:30') },
				{ at: b(13) + beats(2), slate: sat('8:02:53') },
				{ at: b(14), slate: sat('8:03:00') },
			],
			actions: [
				...mainPopupActions(b(7) + beats(0.5), b(7) + beats(2.5)),
				...favoriteActions(b(12) + beats(1)),
			],
		},
		{
			id: 'detail',
			page: 'popup',
			loadAt: 0,
			profile: 'plain',
			reveal: 'off',
			registered: true,
			clock: [{ at: b(11), slate: sat('7:47:28') }],
			actions: [
				{ at: 1, kind: 'click', selector: kentuckyCard },
				{ at: b(11) + beats(0.5), kind: 'scrollTo', selector: '.popup-container', target: '.game-detail-chart-card', offset: 12, over: beats(2.5) },
			],
		},
	],
	tabs: [
		{ at: b(3), tabId: 101, via: 'cut' },
		{ at: b(8) + beats(1), tabId: 103, via: 'swap' },
		{ at: b(9) + beats(1), tabId: 101, via: 'back' },
		{ at: b(10) + beats(1), tabId: 105, via: 'swap' },
		{ at: b(11), tabId: 101, via: 'cut' },
	],
	managedFrom: b(7) + beats(2.5),
	cues: [
		{ at: 0.2, kind: 'dot', step: 0 },
		{ at: 1.0, kind: 'whoosh', length: 0.6, gain: 0.5 },
		{ at: b(3) - 0.25, kind: 'whoosh', length: 0.7 },
		{ at: b(4), kind: 'whoosh', length: 0.5, pan: 0.4 },
		{ at: b(7) + beats(0.5), kind: 'tick' },
		{ at: b(7) + beats(2.5), kind: 'tick' },
		{ at: b(8) + beats(1) - 0.5, kind: 'dot', step: 1 },
		{ at: b(8) + beats(1), kind: 'swap' },
		{ at: b(8) + beats(1), kind: 'whoosh', length: 0.45, pan: -0.3 },
		{ at: b(9) + beats(1) - 0.5, kind: 'dot', step: 2 },
		{ at: b(9) + beats(1), kind: 'swap' },
		{ at: b(10) + beats(1) - 0.5, kind: 'dot', step: 3 },
		{ at: b(10) + beats(1), kind: 'swap' },
		{ at: b(10) + beats(2.6), kind: 'swell', length: 1.2, gain: 0.6 },
		{ at: b(11) - 0.15, kind: 'whoosh', length: 0.35, gain: 0.55 },
		{ at: b(12) + beats(1), kind: 'dot', step: 4 },
		{ at: b(13), kind: 'confetti', gain: 0.8 },
		{ at: b(13) + beats(1.8), kind: 'swell', length: 2 },
		{ at: b(13) + beats(2), kind: 'confetti', gain: 1.2 },
		{ at: b(14) + beats(1.5), kind: 'whoosh', length: 0.8 },
		{ at: b(15) + beats(2), kind: 'dot', step: 0, gain: 1.2 },
	],
};

export default cut30;
