import { bar, beats, barSeconds } from '../timing';
import type { Cut } from './cutTypes';
import { favoriteActions, kentuckyCard, mainPopupActions, sat } from './shared';

const b = bar;
const flickTabs = [103, 104, 105, 102, 103, 104, 105, 101];

// 32 bars. Every switch below is the one the shipped rule made that night (sensitivity 4, 45s
// cooldown, the five tabs in data/tabs.ts); the clocks are set so each lands on the beat.
const cut60: Cut = {
	id: '60',
	bars: 32,
	duration: 32 * barSeconds,
	sections: [
		{ fromBar: 1, toBar: 6, part: 'intro' },
		{ fromBar: 7, toBar: 12, part: 'build' },
		{ fromBar: 13, toBar: 13, part: 'drop' },
		{ fromBar: 14, toBar: 24, part: 'groove' },
		{ fromBar: 25, toBar: 25, part: 'break' },
		{ fromBar: 26, toBar: 29, part: 'peak' },
		{ fromBar: 30, toBar: 32, part: 'outro' },
	],
	shots: [
		{ kind: 'wall', from: 0, to: b(3) + 0.7 },
		{ kind: 'browser', from: b(3), to: b(7) },
		{ kind: 'popupOpen', from: b(7), to: b(9) },
		{ kind: 'ranked', from: b(9), to: b(11) },
		{ kind: 'assign', from: b(11), to: b(13) },
		{ kind: 'swaps', from: b(13), to: b(18) },
		{ kind: 'detail', from: b(18), to: b(19) },
		{ kind: 'scorebugs', from: b(19), to: b(20) },
		{ kind: 'boxScore', from: b(20), to: b(21) },
		{ kind: 'settings', from: b(21), to: b(23) },
		{ kind: 'guide', from: b(23), to: b(24) },
		{ kind: 'leagues', from: b(24), to: b(25) },
		{ kind: 'favorite', from: b(25), to: b(26) },
		{ kind: 'payoff', from: b(26), to: b(30) },
		{ kind: 'endCard', from: b(30), to: b(33) },
	],
	supers: [
		{ key: 'watchOne', from: b(3) + beats(1), to: b(5) + beats(2), place: 'top' },
		{ key: 'otherGames', from: b(7) + beats(2), to: b(9), place: 'top' },
		{ key: 'powerScore', from: b(9) + beats(1), to: b(11), place: 'left' },
		{ key: 'switches', from: b(13) + beats(1), to: b(15), place: 'top' },
		{ key: 'andBack', from: b(15) + beats(1), to: b(16), place: 'top' },
		{ key: 'seeWhy', from: b(18), to: b(19), place: 'left' },
		{ key: 'yours', from: b(21), to: b(23), place: 'left' },
		{ key: 'gotTeam', from: b(25), to: b(26), place: 'left' },
	],
	popups: [
		{
			id: 'main',
			page: 'popup',
			loadAt: b(7),
			profile: 'plain',
			reveal: 'quick',
			registered: false,
			clock: [
				{ at: b(7), slate: sat('7:27:40') },
				{ at: b(9) + beats(1), slate: sat('7:28:30') },
				{ at: b(9) + beats(3), slate: sat('7:28:50') },
				{ at: b(11), slate: sat('7:29:30') },
				{ at: b(13) - beats(1), slate: sat('7:32:55') },
				{ at: b(13) + beats(1), slate: sat('7:33:16') },
				{ at: b(15), slate: sat('7:33:40') },
				{ at: b(15), slate: sat('7:35:05') },
				{ at: b(15) + beats(1), slate: sat('7:35:18') },
				{ at: b(16), slate: sat('7:35:40') },
				{ at: b(16), slate: sat('7:48:00') },
				{ at: b(16) + beats(1), slate: sat('7:48:11') },
				{ at: b(16) + beats(2.5), slate: sat('7:48:50') },
				{ at: b(17), slate: sat('7:49:00') },
				{ at: b(17), slate: sat('7:54:10') },
				{ at: b(17) + beats(1), slate: sat('7:54:21') },
				{ at: b(18), slate: sat('7:54:40') },
				{ at: b(25), slate: sat('7:59:00') },
				{ at: b(26), slate: sat('8:01:30') },
				{ at: b(26) + beats(3), slate: sat('8:01:51') },
				{ at: b(28) - beats(0.5), slate: sat('8:02:45') },
				{ at: b(28) + beats(0.5), slate: sat('8:02:53') },
				{ at: b(29) + beats(2), slate: sat('8:03:00') },
			],
			actions: [
				...mainPopupActions(b(11) + beats(1), b(12) + beats(0.5)),
				...favoriteActions(b(25) + beats(1)),
			],
		},
		{
			id: 'detail',
			page: 'popup',
			loadAt: 0,
			profile: 'plain',
			reveal: 'off',
			registered: true,
			clock: [{ at: b(18), slate: sat('7:47:28') }],
			actions: [
				{ at: 1, kind: 'click', selector: kentuckyCard },
				{ at: b(18) + beats(0.5), kind: 'scrollTo', selector: '.popup-container', target: '.game-detail-chart-card', offset: 12, over: beats(2.5) },
			],
		},
		{
			id: 'list',
			page: 'popup',
			loadAt: 0,
			profile: 'plain',
			reveal: 'off',
			registered: true,
			clock: [{ at: b(19), slate: sat('7:47:31') }],
			actions: [
				{ at: b(19) - 0.5, kind: 'scrollTo', selector: '.popup-container', target: kentuckyCard, offset: 76, over: 0.3 },
				{ at: b(19) + beats(1.8), kind: 'scrollTo', selector: '.popup-container', target: '[data-glide-key="401907985"] .game-card', offset: 76, over: 0.15 },
			],
		},
		{
			id: 'box',
			page: 'popup',
			loadAt: 0,
			profile: 'plain',
			reveal: 'off',
			registered: true,
			clock: [{ at: b(20), slate: sat('7:47:31') }],
			actions: [
				{ at: 1, kind: 'click', selector: kentuckyCard },
				{ at: 2, kind: 'click', selector: '#gd-tab-401856709-box' },
			],
		},
		{
			id: 'settings',
			page: 'popup',
			loadAt: 0,
			profile: 'plain',
			reveal: 'off',
			registered: true,
			clock: [{ at: b(21), slate: sat('7:50:00') }],
			actions: [
				{ at: 1, kind: 'click', selector: 'button[aria-label="Settings"]' },
				{ at: 1.5, kind: 'click', selector: '#settingsGroup-scoring' },
				{ at: b(21) + beats(1), kind: 'click', selector: '#scoringModeSelect' },
				{ at: b(21) + beats(2), kind: 'click', selector: '#scoringModeSelect + .dropdown-menu li:nth-child(2) button' },
				{ at: b(21) + beats(3), kind: 'click', selector: '#scoringModeSelect' },
				{ at: b(22), kind: 'click', selector: '#scoringModeSelect + .dropdown-menu li:nth-child(3) button' },
				{ at: b(22) + beats(1), kind: 'click', selector: '.setup-header' },
				{ at: b(22) + beats(1.5), kind: 'click', selector: '#settingsGroup-switching' },
				{ at: b(22) + beats(2.5), kind: 'value', selector: '#sensitivity-range', value: '6' },
				{ at: b(22) + beats(3), kind: 'value', selector: '#sensitivity-range', value: '3' },
			],
		},
		{
			id: 'guide',
			page: 'guide',
			loadAt: 0,
			profile: 'plain',
			reveal: 'off',
			registered: true,
			clock: [{ at: b(23), slate: sat('7:50:00') }],
			actions: [],
			width: 1280,
			height: 720,
		},
	],
	tabs: [
		{ at: b(3), tabId: 102, via: 'cut' },
		...flickTabs.map((tabId, index) => ({ at: b(5) + beats(index), tabId, via: 'flick' as const })),
		{ at: b(13) + beats(1), tabId: 103, via: 'swap' },
		{ at: b(15) + beats(1), tabId: 101, via: 'back' },
		{ at: b(16) + beats(1), tabId: 105, via: 'swap' },
		{ at: b(17) + beats(1), tabId: 101, via: 'back' },
	],
	managedFrom: b(12) + beats(0.5),
	cues: [
		{ at: 0.2, kind: 'dot', step: 0 },
		{ at: 1.0, kind: 'whoosh', length: 0.6, gain: 0.5 },
		{ at: b(3) - 0.25, kind: 'whoosh', length: 0.7 },
		...flickTabs.map((_, index) => ({ at: b(5) + beats(index), kind: 'tick' as const, gain: 0.9 })),
		{ at: b(7), kind: 'whoosh', length: 0.5, pan: 0.4 },
		{ at: b(11) + beats(1), kind: 'tick' },
		{ at: b(12) + beats(0.5), kind: 'tick' },
		{ at: b(13) + beats(1) - 0.5, kind: 'dot', step: 1 },
		{ at: b(13) + beats(1), kind: 'swap' },
		{ at: b(13) + beats(1), kind: 'whoosh', length: 0.45, pan: -0.3 },
		{ at: b(15) + beats(1) - 0.5, kind: 'dot', step: 2 },
		{ at: b(15) + beats(1), kind: 'swap' },
		{ at: b(16) + beats(1) - 0.5, kind: 'dot', step: 3 },
		{ at: b(16) + beats(1), kind: 'swap' },
		{ at: b(16) + beats(2.6), kind: 'swell', length: 1.2, gain: 0.6 },
		{ at: b(17) + beats(1) - 0.5, kind: 'dot', step: 4 },
		{ at: b(17) + beats(1), kind: 'swap' },
		...[18, 19, 20, 21, 23, 24].map(number => ({ at: b(number) - 0.15, kind: 'whoosh' as const, length: 0.35, gain: 0.55 })),
		{ at: b(24) + 1.0, kind: 'dot', step: 2 },
		{ at: b(25) + beats(1), kind: 'dot', step: 5 },
		{ at: b(26) + beats(3), kind: 'confetti' },
		{ at: b(28) - beats(0.2), kind: 'swell', length: 2.4 },
		{ at: b(28), kind: 'confetti', gain: 1.2 },
		{ at: b(30) + beats(1.5), kind: 'whoosh', length: 0.8 },
		{ at: b(31) + beats(2), kind: 'dot', step: 0, gain: 1.2 },
	],
};

export default cut60;
