export { scoreGame, createSignalInput, signalPoints, boostPoints } from './compose';
export { builtInModes, blowoutsMode, classicMode, defineMode, fantasyMode, getMode } from './modes';
export { blowoutsSignals } from './signals/blowouts';
export { fantasySignals } from './signals/fantasy';
export { computeFantasyPoints, defaultFantasyScoring, fantasySportOf, resolveFantasyScoring } from './fantasyScoring';
export type { FantasyRule, FantasySport } from './fantasyScoring';
export { goAheadRunBoost } from './boosts/goAheadRun';
export { twoMinuteDrillBoost } from './boosts/twoMinuteDrill';
export { noHitterBoost } from './boosts/noHitter';
export { redCardBoost } from './boosts/redCard';
export { upsetWatchBoost, upsetRoutBoost, underdogProbability } from './boosts/upsetWatch';
export { stakesBoost } from './boosts/stakes';
export { classicSignals, closenessSignal, lateGameSignal, momentumSignal, leadChangesSignal, comebackSignal, applyProgressFloor, findLeadChanges } from './signals/classic';
export { scoringOpportunityBoost } from './boosts/scoringOpportunity';
export { postseasonBoostShare } from './postseason';
export { renderReasonEnglish, renderReasonsEnglish } from './reasons';
export { resolveLeagueConfig, resolveSportConfig } from './config';
export { getGameProgress, scoreMargin } from './progress';
export { computeGameProgress, computePowerScore, computeScoringOpportunityBoost, computeWinProbVarianceScore, isPlayFrozen, normalizePowerScoreResult } from './scorer';
export * from './types';
export * from './constants';
