// Jest stub for the `#i18n` virtual module generated by @wxt-dev/i18n.
// The real module resolves messages via the browser i18n runtime (compiled
// _locales), which isn't available under Jest. This stub loads the English
// locale file directly and reimplements the subset of `i18n.t` behavior the
// tests rely on: nested-key lookup, `$1`..`$9` positional and `{named}`
// substitutions, and `0`/`1`/`n` plural forms.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const messages = JSON.parse(readFileSync(join(__dirname, '../../locales/en.json'), 'utf8')) as Record<string, unknown>;

const lookup = (key: string): unknown =>
	key.split('.').reduce<unknown>((node, part) => (
		node && typeof node === 'object' ? (node as Record<string, unknown>)[part] : undefined
	), messages);

const applySubstitutions = (template: string, subs: unknown): string => {
	if (Array.isArray(subs)) {
		return template.replace(/\$(\d)/g, (_, n) => String(subs[Number(n) - 1] ?? ''));
	}
	if (subs && typeof subs === 'object') {
		return template.replace(/\{(\w+)\}/g, (_, name) => String((subs as Record<string, unknown>)[name] ?? ''));
	}
	return template;
};

const t = (key: string, subsOrCount?: unknown, subs?: unknown): string => {
	const entry = lookup(key);
	if (typeof entry === 'string') return applySubstitutions(entry, subsOrCount);
	// Plural form: entry is an object keyed by 0/1/n and count is passed as subsOrCount.
	if (entry && typeof entry === 'object' && typeof subsOrCount === 'number') {
		const forms = entry as Record<string, string>;
		const count = subsOrCount;
		const form = forms[String(count)] ?? forms.n ?? forms['1'] ?? '';
		return applySubstitutions(form, subs ?? [count]);
	}
	return key;
};

export const i18n = { t };
